In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import datasets, svm
from sklearn.datasets import load_digits

In [2]:
df = pd.read_csv("../Datasets/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [26]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)

In [28]:
X_train.values

array(["Now? I'm going out 4 dinner soon..",
       'I had been hoping i would not have to send you this message. My rent is due and i dont have enough for it. My reserves are completely gone. Its a loan i need and was hoping you could her. The balance is  &lt;#&gt; . Is there a way i could get that from you, till mid march when i hope to pay back.',
       'There bold 2  &lt;#&gt; . Is that yours', ...,
       'Hello, As per request from  &lt;#&gt;  Rs.5 has been transfered to you',
       "I'm reading the text i just sent you. Its meant to be a joke. So read it in that light",
       'Is there coming friday is leave for pongal?do you get any news from your work place.'],
      dtype=object)

In [29]:
## lets convert the text message to vectors

from sklearn.feature_extraction.text import CountVectorizer
x = CountVectorizer()
X_train_count = x.fit_transform(X_train.values)

In [30]:
## there are 3 types of Naive Bayes
## Gaussian, Bernoulli and Multinominal one
## learn about them

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [31]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = x.transform(emails)
model.predict(emails_count)

## first one as non spam, second as spam

array([0, 1], dtype=int64)

In [32]:
X_test_count = x.transform(X_test)
model.score(X_test_count,y_test)

0.9863603732950467

In [34]:
## just use the pipeline instead of using the manual method to

from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [35]:
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9863603732950467

In [37]:
clf.predict(["Hello i am sanket"])

array([0], dtype=int64)

In [40]:
clf.predict(['Join NEU with full 100% scholarship']) 
## spam

array([1], dtype=int64)